"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_grey)\
$os\
$username\
[](bg:color_brown fg:color_grey)\
$directory\
[](fg:color_brown bg:color_teal)\
$git_branch\
$git_status\
[](fg:color_teal bg:color_beige)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_beige bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'Ryuuko'

[palettes.Ryuuko]
color_fg0 = '#ECECEC'
color_bg1 = '#B18A73'
color_bg3 = '#698E95'
color_beige = '#B2A990'
color_teal = '#66907D'
color_green = '#66907D'
color_grey = '#5C6F79'
color_purple = '#9242A9'
color_red = '#C83933'
color_brown = '#865F5B'

[os]
disabled = false
style = "bg:color_grey fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_grey fg:color_fg0"
style_root = "bg:color_grey fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg0 bg:color_brown"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_teal"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_teal)]($style)'

[git_status]
style = "bg:color_teal"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_teal)]($style)'

[nodejs]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[c]
symbol = " "
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[cpp]
symbol = " "
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[rust]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[golang]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[php]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[java]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[kotlin]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[haskell]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[python]
symbol = ""
style = "bg:color_beige"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_beige)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[pixi]
style = "bg:color_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg0 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_brown)'
